spring:
  jpa:
    show-sql: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate.ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/posjpa
    username: root
    password: rootp
